/*******************************************************************************/
/*  This file is auto-generated by GUIX Studio. Do not edit this file by hand. */
/*  Modifications to this file should only be made by running the GUIX Studio  */
/*  application and re-generating the application resource file(s). For more   */
/*  information please refer to the GUIX Studio user's guide, or visit our web */
/*  site at www.expresslogic.com.                                              */
/*                                                                             */
/*  GUIX Studio Revision 5.4.1.1                                               */
/*  Date (dd.mm.yyyy): 25. 9.2019   Time (hh:mm): 23:34                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_CANVAS 0
#define GX_COLOR_ID_WIDGET_FILL 1
#define GX_COLOR_ID_WINDOW_FILL 2
#define GX_COLOR_ID_DEFAULT_BORDER 3
#define GX_COLOR_ID_WINDOW_BORDER 4
#define GX_COLOR_ID_TEXT 5
#define GX_COLOR_ID_SELECTED_TEXT 6
#define GX_COLOR_ID_SELECTED_FILL 7
#define GX_COLOR_ID_SHADOW 8
#define GX_COLOR_ID_SHINE 9
#define GX_COLOR_ID_BTN_BORDER 10
#define GX_COLOR_ID_BTN_UPPER 11
#define GX_COLOR_ID_BTN_LOWER 12
#define GX_COLOR_ID_BTN_TEXT 13
#define GX_COLOR_ID_SCROLL_FILL 14
#define GX_COLOR_ID_SCROLL_BUTTON 15
#define GX_COLOR_ID_TEXT_INPUT_TEXT 16
#define GX_COLOR_ID_TEXT_INPUT_FILL 17
#define GX_COLOR_ID_SLIDER_TICK 18
#define GX_COLOR_ID_SLIDER_GROOVE_TOP 19
#define GX_COLOR_ID_SLIDER_GROOVE_BOTTOM 20
#define GX_COLOR_ID_SLIDER_NEEDLE_OUTLINE 21
#define GX_COLOR_ID_SLIDER_NEEDLE_FILL 22
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE1 23
#define GX_COLOR_ID_SLIDER_NEEDLE_LINE2 24
#define GX_COLOR_ID_BTN_INC_SELECTED 25
#define GX_COLOR_ID_BTN_INC_NORMAL 26
#define GX_COLOR_ID_BTN_DEC_NORMAL 27
#define GX_COLOR_ID_BTN_DEC_SELECTED 28
#define GX_COLOR_ID_NEW_COLOR 29
#define GX_COLOR_ID_BLUE_SYSTEM 30
#define DISPLAY_1_COLOR_TABLE_SIZE 31

/* Font ID definitions                                                         */

#define GX_FONT_ID_SYSTEM 0
#define GX_FONT_ID_BUTTON 1
#define GX_FONT_ID_PROMPT 2
#define GX_FONT_ID_TEXT_INPUT 3
#define GX_FONT_ID_REGISTER 4
#define DISPLAY_1_FONT_TABLE_SIZE 5

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_RADIO_ON 1
#define GX_PIXELMAP_ID_RADIO_OFF 2
#define GX_PIXELMAP_ID_CHECKBOX_ON 3
#define GX_PIXELMAP_ID_CHECKBOX_OFF 4
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_LBL_DSE 1
#define GX_STRING_ID_LBL_START 2
#define GX_STRING_ID_LBL_INFO_DUTY_CYCLE 3
#define GX_STRING_ID_LBL_INFO_SPEED 4
#define GX_STRING_ID_LBL_INFO_SET_POINT 5
#define GX_STRING_ID_LBL_STOP 6
#define GX_STRING_ID_LBL_INC 7
#define GX_STRING_ID_LBL_DEC 8
#define GX_STRING_ID_STRING_1 9
#define GX_STRING_ID_STRING_2 10
#define GX_STRING_ID_STRING_3 11
#define GX_STRING_ID_STRING_4 12
#define GX_STRING_ID_STRING_5 13
#define GX_STRING_ID_STRING_6 14
#define GX_STRING_ID_STRING_7 15
#define GX_STRING_ID_LBL_INFO_DEV 16
#define GX_STRING_ID_LBL_INFO_VER 17
#define GX_STRING_ID_STRING_10 18
#define GX_STRING_ID_STRING_8 19
#define GX_STRING_ID_STRING_9 20
#define GX_STRING_ID_STRING_11 21
#define GX_STRING_ID_STRING_12 22
#define GX_STRING_ID_STRING_13 23
#define GX_STRING_ID_STRING_14 24
#define GX_STRING_ID_STRING_15 25
#define GX_STRING_ID_STRING_16 26
#define GX_STRING_ID_STRING_17 27
#define GX_STRING_ID_STRING_18 28
#define GX_STRING_ID_STRING_19 29
#define GX_STRING_ID_STRING_20 30
#define GX_STRING_ID_STRING_21 31
#define GX_STRING_ID_STRING_22 32
#define GX_STRING_ID_STRING_23 33
#define GX_STRING_ID_STRING_24 34
#define GX_STRING_ID_STRING_25 35
#define GX_STRING_ID_STRING_26 36
#define GX_STRING_ID_STRING_27 37
#define GX_STRING_ID_STRING_28 38
#define GX_STRING_ID_STRING_29 39
#define GX_STRING_ID_STRING_30 40
#define GX_STRING_ID_STRING_31 41
#define GX_STRING_ID_STRING_32 42
#define GX_STRING_ID_STRING_33 43
#define GX_STRING_ID_STRING_34 44
#define GX_STRING_ID_STRING_35 45
#define GX_STRING_ID_STRING_36 46
#define GX_STRING_ID_STRING_37 47
#define GX_STRING_ID_STRING_38 48
#define GX_STRING_ID_STRING_39 49
#define GX_STRING_ID_STRING_40 50
#define GX_STRING_ID_STRING_41 51
#define GX_STRING_ID_STRING_42 52
#define GX_STRING_ID_STRING_43 53
#define GX_STRING_ID_STRING_44 54
#define GX_STRING_ID_STRING_45 55
#define GX_STRING_ID_STRING_46 56
#define GX_STRING_ID_STRING_47 57
#define GX_STRING_ID_STRING_48 58
#define GX_STRING_ID_STRING_49 59
#define GX_STRING_ID_STRING_50 60
#define GX_STRING_ID_STRING_51 61
#define GX_STRING_ID_STRING_52 62
#define GX_STRING_ID_STRING_53 63
#define GX_STRING_ID_STRING_54 64
#define GX_STRING_ID_STRING_55 65
#define GX_STRING_ID_STRING_56 66
#define GX_STRING_ID_STRING_57 67
#define GX_STRING_ID_STRING_58 68
#define GX_STRING_ID_STRING_59 69
#define GX_STRING_ID_STRING_60 70
#define GX_STRING_ID_STRING_61 71
#define GX_STRING_ID_STRING_62 72
#define DISPLAY_1_STRING_TABLE_SIZE 73

#endif                                       /* sentry                         */
